# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdiiVvTFJL0on57ncY-Rj1Vc_I_hYsmD
"""

import asyncio
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

TOKEN = input("Bot Token: ").strip()

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "❤️ Welcome to Life After 35!\n\n"
        "Bot is working successfully."
    )

async def main():
    app = Application.builder().token(TOKEN).build()

    app.add_handler(CommandHandler("start", start))

    print("Life After 35 Bot is starting...")

    await app.initialize()
    await app.start()
    await app.updater.start_polling()

    print("✅ Bot is ONLINE")

    await asyncio.Event().wait()

await main()